import { SceneItem } from "./types";

export const SCENES: SceneItem[] = [
  {
    id: "01",
    act: 1,
    page: 1,
    pagePath: "Knights_of_Sidonia/photos/page_001.jpg",
    speaker: "Narrator",
    motion: "pan-spread-left",
    audioFile: "Knights_of_Sidonia/audio/line_01.mp3",
    durationInFrames: 152,
  },
  {
    id: "02",
    act: 1,
    page: 3,
    pagePath: "Knights_of_Sidonia/photos/page_003.jpg",
    speaker: "Narrator",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_02.mp3",
    durationInFrames: 167,
  },
  {
    id: "03",
    act: 1,
    page: 5,
    pagePath: "Knights_of_Sidonia/photos/page_005.jpg",
    speaker: "Narrator",
    motion: "zoom-top-to-bottom",
    audioFile: "Knights_of_Sidonia/audio/line_03.mp3",
    durationInFrames: 133,
  },
  {
    id: "04",
    act: 1,
    page: 7,
    pagePath: "Knights_of_Sidonia/photos/page_007.jpg",
    speaker: "Narrator",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_04.mp3",
    durationInFrames: 98,
  },
  {
    id: "05",
    act: 1,
    page: 9,
    pagePath: "Knights_of_Sidonia/photos/page_009.jpg",
    speaker: "Narrator",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_05.mp3",
    durationInFrames: 260,
  },
  {
    id: "06",
    act: 2,
    page: 10,
    pagePath: "Knights_of_Sidonia/photos/page_010.jpg",
    speaker: "Narrator",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_06.mp3",
    durationInFrames: 242,
  },
  {
    id: "07",
    act: 2,
    page: 12,
    pagePath: "Knights_of_Sidonia/photos/page_012.jpg",
    speaker: "Nagate",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_07.mp3",
    durationInFrames: 118,
  },
  {
    id: "08",
    act: 2,
    page: 14,
    pagePath: "Knights_of_Sidonia/photos/page_014.jpg",
    speaker: "Narrator",
    motion: "scroll-up",
    audioFile: "Knights_of_Sidonia/audio/line_08.mp3",
    durationInFrames: 188,
  },
  {
    id: "09",
    act: 2,
    page: 17,
    pagePath: "Knights_of_Sidonia/photos/page_017.jpg",
    speaker: "Nagate",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_09.mp3",
    durationInFrames: 75,
  },
  {
    id: "10",
    act: 2,
    page: 17,
    pagePath: "Knights_of_Sidonia/photos/page_017.jpg",
    speaker: "Narrator",
    motion: "pan-spread-left",
    audioFile: "Knights_of_Sidonia/audio/line_10.mp3",
    durationInFrames: 141,
  },
  {
    id: "11",
    act: 3,
    page: 19,
    pagePath: "Knights_of_Sidonia/photos/page_019.jpg",
    speaker: "Worker",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_11.mp3",
    durationInFrames: 113,
  },
  {
    id: "12",
    act: 3,
    page: 19,
    pagePath: "Knights_of_Sidonia/photos/page_019.jpg",
    speaker: "Nagate",
    motion: "zoom-top-to-bottom",
    audioFile: "Knights_of_Sidonia/audio/line_12.mp3",
    durationInFrames: 107,
  },
  {
    id: "13",
    act: 3,
    page: 21,
    pagePath: "Knights_of_Sidonia/photos/page_021.jpg",
    speaker: "Narrator",
    motion: "pan-spread-left",
    audioFile: "Knights_of_Sidonia/audio/line_13.mp3",
    durationInFrames: 126,
  },
  {
    id: "14",
    act: 3,
    page: 23,
    pagePath: "Knights_of_Sidonia/photos/page_023.jpg",
    speaker: "Narrator",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_14.mp3",
    durationInFrames: 213,
  },
  {
    id: "15",
    act: 3,
    page: 24,
    pagePath: "Knights_of_Sidonia/photos/page_024.jpg",
    speaker: "Investigator",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_15.mp3",
    durationInFrames: 180,
  },
  {
    id: "16",
    act: 3,
    page: 24,
    pagePath: "Knights_of_Sidonia/photos/page_024.jpg",
    speaker: "Nagate",
    motion: "zoom-top-to-bottom",
    audioFile: "Knights_of_Sidonia/audio/line_16.mp3",
    durationInFrames: 103,
  },
  {
    id: "17",
    act: 4,
    page: 25,
    pagePath: "Knights_of_Sidonia/photos/page_025.jpg",
    speaker: "Ochiai",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_17.mp3",
    durationInFrames: 176,
  },
  {
    id: "18",
    act: 4,
    page: 25,
    pagePath: "Knights_of_Sidonia/photos/page_025.jpg",
    speaker: "Nagate",
    motion: "zoom-top-to-bottom",
    audioFile: "Knights_of_Sidonia/audio/line_18.mp3",
    durationInFrames: 70,
  },
  {
    id: "19",
    act: 4,
    page: 28,
    pagePath: "Knights_of_Sidonia/photos/page_028.jpg",
    speaker: "Ochiai",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_19.mp3",
    durationInFrames: 237,
  },
  {
    id: "20",
    act: 4,
    page: 27,
    pagePath: "Knights_of_Sidonia/photos/page_027.jpg",
    speaker: "Narrator",
    motion: "scroll-up",
    audioFile: "Knights_of_Sidonia/audio/line_20.mp3",
    durationInFrames: 190,
  },
  {
    id: "21",
    act: 4,
    page: 30,
    pagePath: "Knights_of_Sidonia/photos/page_030.jpg",
    speaker: "Kobayashi",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_21.mp3",
    durationInFrames: 166,
  },
  {
    id: "22",
    act: 4,
    page: 31,
    pagePath: "Knights_of_Sidonia/photos/page_031.jpg",
    speaker: "Lala",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_22.mp3",
    durationInFrames: 164,
  },
  {
    id: "23",
    act: 4,
    page: 31,
    pagePath: "Knights_of_Sidonia/photos/page_031.jpg",
    speaker: "Nagate",
    motion: "zoom-top-to-bottom",
    audioFile: "Knights_of_Sidonia/audio/line_23.mp3",
    durationInFrames: 90,
  },
  {
    id: "24",
    act: 5,
    page: 33,
    pagePath: "Knights_of_Sidonia/photos/page_033.jpg",
    speaker: "Shizuka",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_24.mp3",
    durationInFrames: 125,
  },
  {
    id: "25",
    act: 5,
    page: 34,
    pagePath: "Knights_of_Sidonia/photos/page_034.jpg",
    speaker: "Instructor",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_25.mp3",
    durationInFrames: 284,
  },
  {
    id: "26",
    act: 5,
    page: 36,
    pagePath: "Knights_of_Sidonia/photos/page_036.jpg",
    speaker: "Narrator",
    motion: "pan-spread-left",
    audioFile: "Knights_of_Sidonia/audio/line_26.mp3",
    durationInFrames: 134,
  },
  {
    id: "27",
    act: 5,
    page: 37,
    pagePath: "Knights_of_Sidonia/photos/page_037.jpg",
    speaker: "Cadets",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_27.mp3",
    durationInFrames: 116,
  },
  {
    id: "28",
    act: 5,
    page: 37,
    pagePath: "Knights_of_Sidonia/photos/page_037.jpg",
    speaker: "Nagate",
    motion: "zoom-top-to-bottom",
    audioFile: "Knights_of_Sidonia/audio/line_28.mp3",
    durationInFrames: 118,
  },
  {
    id: "29",
    act: 5,
    page: 39,
    pagePath: "Knights_of_Sidonia/photos/page_039.jpg",
    speaker: "Nagate",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_29.mp3",
    durationInFrames: 119,
  },
  {
    id: "30",
    act: 5,
    page: 40,
    pagePath: "Knights_of_Sidonia/photos/page_040.jpg",
    speaker: "Honoka",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_30.mp3",
    durationInFrames: 103,
  },
  {
    id: "31",
    act: 6,
    page: 42,
    pagePath: "Knights_of_Sidonia/photos/page_042.jpg",
    speaker: "Elder",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_31.mp3",
    durationInFrames: 126,
  },
  {
    id: "32",
    act: 6,
    page: 45,
    pagePath: "Knights_of_Sidonia/photos/page_045.jpg",
    speaker: "Kobayashi",
    motion: "zoom-top-to-bottom",
    audioFile: "Knights_of_Sidonia/audio/line_32.mp3",
    durationInFrames: 147,
  },
  {
    id: "33",
    act: 6,
    page: 46,
    pagePath: "Knights_of_Sidonia/photos/page_046.jpg",
    speaker: "Narrator",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_33.mp3",
    durationInFrames: 145,
  },
  {
    id: "34",
    act: 7,
    page: 47,
    pagePath: "Knights_of_Sidonia/photos/page_047.jpg",
    speaker: "Narrator",
    motion: "pan-spread-left",
    audioFile: "Knights_of_Sidonia/audio/line_34.mp3",
    durationInFrames: 169,
  },
  {
    id: "35",
    act: 7,
    page: 49,
    pagePath: "Knights_of_Sidonia/photos/page_049.jpg",
    speaker: "Nagate",
    motion: "scroll-up",
    audioFile: "Knights_of_Sidonia/audio/line_35.mp3",
    durationInFrames: 79,
  },
  {
    id: "36",
    act: 7,
    page: 50,
    pagePath: "Knights_of_Sidonia/photos/page_050.jpg",
    speaker: "Narrator",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_36.mp3",
    durationInFrames: 168,
  },
  {
    id: "37",
    act: 7,
    page: 50,
    pagePath: "Knights_of_Sidonia/photos/page_050.jpg",
    speaker: "Kobayashi",
    motion: "zoom-top-to-bottom",
    audioFile: "Knights_of_Sidonia/audio/line_37.mp3",
    durationInFrames: 111,
  },
  {
    id: "38",
    act: 7,
    page: 50,
    pagePath: "Knights_of_Sidonia/photos/page_050.jpg",
    speaker: "Nagate",
    motion: "pan-spread-left",
    audioFile: "Knights_of_Sidonia/audio/line_38.mp3",
    durationInFrames: 142,
  },
  {
    id: "39",
    act: 8,
    page: 1,
    pagePath: "Knights_of_Sidonia/chapter_2/page_001.jpg",
    speaker: "Narrator",
    motion: "pan-spread-left",
    audioFile: "Knights_of_Sidonia/audio/line_39.mp3",
    durationInFrames: 222,
  },
  {
    id: "40",
    act: 8,
    page: 3,
    pagePath: "Knights_of_Sidonia/chapter_2/page_003.jpg",
    speaker: "Kunato",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_40.mp3",
    durationInFrames: 206,
  },
  {
    id: "41",
    act: 8,
    page: 5,
    pagePath: "Knights_of_Sidonia/chapter_2/page_005.jpg",
    speaker: "Nagate",
    motion: "zoom-top-to-bottom",
    audioFile: "Knights_of_Sidonia/audio/line_41.mp3",
    durationInFrames: 166,
  },
  {
    id: "42",
    act: 8,
    page: 7,
    pagePath: "Knights_of_Sidonia/chapter_2/page_007.jpg",
    speaker: "Shizuka",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_42.mp3",
    durationInFrames: 177,
  },
  {
    id: "43",
    act: 9,
    page: 9,
    pagePath: "Knights_of_Sidonia/chapter_2/page_009.jpg",
    speaker: "Narrator",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_43.mp3",
    durationInFrames: 183,
  },
  {
    id: "44",
    act: 9,
    page: 12,
    pagePath: "Knights_of_Sidonia/chapter_2/page_012.jpg",
    speaker: "Control",
    motion: "zoom-top-to-bottom",
    audioFile: "Knights_of_Sidonia/audio/line_44.mp3",
    durationInFrames: 234,
  },
  {
    id: "45",
    act: 9,
    page: 15,
    pagePath: "Knights_of_Sidonia/chapter_2/page_015.jpg",
    speaker: "Instructor",
    motion: "scroll-up",
    audioFile: "Knights_of_Sidonia/audio/line_45.mp3",
    durationInFrames: 197,
  },
  {
    id: "46",
    act: 9,
    page: 18,
    pagePath: "Knights_of_Sidonia/chapter_2/page_018.jpg",
    speaker: "Nagate",
    motion: "pan-spread-left",
    audioFile: "Knights_of_Sidonia/audio/line_46.mp3",
    durationInFrames: 80,
  },
  {
    id: "47",
    act: 10,
    page: 20,
    pagePath: "Knights_of_Sidonia/chapter_2/page_020.jpg",
    speaker: "Narrator",
    motion: "pan-spread-left",
    audioFile: "Knights_of_Sidonia/audio/line_47.mp3",
    durationInFrames: 210,
  },
  {
    id: "48",
    act: 10,
    page: 22,
    pagePath: "Knights_of_Sidonia/chapter_2/page_022.jpg",
    speaker: "Shizuka",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_48.mp3",
    durationInFrames: 186,
  },
  {
    id: "49",
    act: 10,
    page: 25,
    pagePath: "Knights_of_Sidonia/chapter_2/page_025.jpg",
    speaker: "Kunato",
    motion: "zoom-top-to-bottom",
    audioFile: "Knights_of_Sidonia/audio/line_49.mp3",
    durationInFrames: 140,
  },
  {
    id: "50",
    act: 11,
    page: 28,
    pagePath: "Knights_of_Sidonia/chapter_2/page_028.jpg",
    speaker: "Narrator",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_50.mp3",
    durationInFrames: 155,
  },
  {
    id: "51",
    act: 11,
    page: 30,
    pagePath: "Knights_of_Sidonia/chapter_2/page_030.jpg",
    speaker: "Control",
    motion: "zoom-top-to-bottom",
    audioFile: "Knights_of_Sidonia/audio/line_51.mp3",
    durationInFrames: 210,
  },
  {
    id: "52",
    act: 11,
    page: 32,
    pagePath: "Knights_of_Sidonia/chapter_2/page_032.jpg",
    speaker: "Kobayashi",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_52.mp3",
    durationInFrames: 145,
  },
  {
    id: "53",
    act: 12,
    page: 1,
    pagePath: "Knights_of_Sidonia/chapter_3/page_001.jpg",
    speaker: "Narrator",
    motion: "pan-spread-left",
    audioFile: "Knights_of_Sidonia/audio/line_53.mp3",
    durationInFrames: 181,
  },
  {
    id: "54",
    act: 12,
    page: 4,
    pagePath: "Knights_of_Sidonia/chapter_3/page_004.jpg",
    speaker: "Shizuka",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_54.mp3",
    durationInFrames: 159,
  },
  {
    id: "55",
    act: 12,
    page: 7,
    pagePath: "Knights_of_Sidonia/chapter_3/page_007.jpg",
    speaker: "Kunato",
    motion: "zoom-top-to-bottom",
    audioFile: "Knights_of_Sidonia/audio/line_55.mp3",
    durationInFrames: 162,
  },
  {
    id: "56",
    act: 12,
    page: 10,
    pagePath: "Knights_of_Sidonia/chapter_3/page_010.jpg",
    speaker: "Narrator",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_56.mp3",
    durationInFrames: 183,
  },
  {
    id: "57",
    act: 13,
    page: 13,
    pagePath: "Knights_of_Sidonia/chapter_3/page_013.jpg",
    speaker: "Narrator",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_57.mp3",
    durationInFrames: 177,
  },
  {
    id: "58",
    act: 13,
    page: 16,
    pagePath: "Knights_of_Sidonia/chapter_3/page_016.jpg",
    speaker: "Shizuka",
    motion: "zoom-top-to-bottom",
    audioFile: "Knights_of_Sidonia/audio/line_58.mp3",
    durationInFrames: 136,
  },
  {
    id: "59",
    act: 13,
    page: 19,
    pagePath: "Knights_of_Sidonia/chapter_3/page_019.jpg",
    speaker: "Kobayashi",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_59.mp3",
    durationInFrames: 195,
  },
  {
    id: "60",
    act: 14,
    page: 21,
    pagePath: "Knights_of_Sidonia/chapter_3/page_021.jpg",
    speaker: "Nagate",
    motion: "pan-spread-left",
    audioFile: "Knights_of_Sidonia/audio/line_60.mp3",
    durationInFrames: 129,
  },
  {
    id: "61",
    act: 14,
    page: 24,
    pagePath: "Knights_of_Sidonia/chapter_3/page_024.jpg",
    speaker: "Narrator",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_61.mp3",
    durationInFrames: 223,
  },
  {
    id: "62",
    act: 14,
    page: 27,
    pagePath: "Knights_of_Sidonia/chapter_3/page_027.jpg",
    speaker: "Kunato",
    motion: "zoom-top-to-bottom",
    audioFile: "Knights_of_Sidonia/audio/line_62.mp3",
    durationInFrames: 162,
  },
  {
    id: "63",
    act: 15,
    page: 29,
    pagePath: "Knights_of_Sidonia/chapter_3/page_029.jpg",
    speaker: "Narrator",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_63.mp3",
    durationInFrames: 201,
  },
  {
    id: "64",
    act: 15,
    page: 31,
    pagePath: "Knights_of_Sidonia/chapter_3/page_031.jpg",
    speaker: "Nagate",
    motion: "zoom-top-to-bottom",
    audioFile: "Knights_of_Sidonia/audio/line_64.mp3",
    durationInFrames: 94,
  },
  {
    id: "65",
    act: 15,
    page: 33,
    pagePath: "Knights_of_Sidonia/chapter_3/page_033.jpg",
    speaker: "Narrator",
    motion: "pan-spread-left",
    audioFile: "Knights_of_Sidonia/audio/line_65.mp3",
    durationInFrames: 213,
  },
  {
    id: "66",
    act: 15,
    page: 34,
    pagePath: "Knights_of_Sidonia/chapter_3/page_034.jpg",
    speaker: "Shizuka",
    motion: "scroll-down",
    audioFile: "Knights_of_Sidonia/audio/line_66.mp3",
    durationInFrames: 105,
  }
];
